[workspace]
resolver = "2"
members = ["arena-postgres",
    "arena",
    "arena-kafka",
    "examples"
]

[workspace.dependencies]
arena = { path = "arena", version = "0.1.0-alpha.1" }
arena-kafka = { path = "arena-kafka", version = "0.1.0-alpha.1" }
arena-postgres = { path = "arena-postgres", version = "0.1.0-alpha.1" }
axum = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio-postgres = "0.7"
postgres = "0.19"
rdkafka = { version = "0.36", features = ["tokio"] }
backon = "1.5.2"
async-trait = "0.1"
env_logger = "0.11"
futures = "0.3"
futures-timer = "3.0.3"
log = "0.4"
testcontainers-modules = "0.14.0"
tokio = "1"
mockall = "0.14.0"