[[image]]
id = "postgres"
image = "postgres"
tag = "17"

[[image]]
id = "kafka_apache"
image = "apache/kafka"
tag = "3.9.1"

[[image]]
id = "kafka_confluent"
image = "confluentinc/cp-kafka"
tag = "7.8.9"

[[image]]
id = "mssql"
image = "mcr.microsoft.com/mssql/server"
tag = "2022-CU25-ubuntu-22.04"

[[image]]
id = "http"
image = "wiremock/wiremock"
tag = "3.13.2"

[[image]]
id = "localstack"
image = "localstack/localstack"
tag = "4.14.0"
