[[image]]
id = "postgres"
image = "postgres"
tag = "18-bookworm"

[[image]]
id = "kafka_apache"
image = "apache/kafka"
tag = "4.3.1"

[[image]]
id = "kafka_confluent"
image = "confluentinc/cp-kafka"
tag = "8.2.2"

[[image]]
id = "mssql"
image = "mcr.microsoft.com/mssql/server"
tag = "2025-CU7-ubuntu-24.04"

[[image]]
id = "http"
image = "wiremock/wiremock"
tag = "3.13.2-alpine"

[[image]]
id = "localstack"
image = "localstack/localstack"
tag = "4.14.0"

[[image]]
id = "temporal"
image = "temporalio/temporal"
tag = "1.8.0"

[[image]]
id = "smtp"
image = "axllent/mailpit"
tag = "v1.30.5"

[[image]]
id = "oracle"
image = "gvenzl/oracle-free"
tag = "23.26.2-slim-faststart"
