[package]
name = "arena-localstack"
version.workspace = true
edition = "2021"
authors = ["David Pope"]
description = "Arena LocalStack implementation (local AWS emulation)"
license = "todo"

[dependencies]
arena = { workspace = true }
arena-container = { workspace = true }
async-trait = { workspace = true }
testcontainers-modules = { workspace = true, features = ["localstack"] }
log = { workspace = true }
futures-timer = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
aws-config = { workspace = true }
aws-sdk-sqs = { workspace = true }
aws-sdk-lambda = { workspace = true }
aws-sdk-eventbridge = { workspace = true }
aws-credential-types = { workspace = true }
aws-smithy-types = { workspace = true }
zip = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
env_logger = { workspace = true }
