[package]
name = "arena"
version.workspace = true
edition = "2021"
authors = ["David Pope"]
description = "The base Arena module containing contracts and core Arena behaviour."
license = "todo"

[lib]
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
tracing-subscriber = { workspace = true }
futures-timer = { workspace = true }
