[package]
name = "arena-executable-component"
version.workspace = true
edition = "2021"
authors = ["David Pope"]
description = "The Arena Execuable Component module containing centrally managed component implmentations that manage a running executable."
license = "todo"

[lib]
path = "src/lib.rs"

[dependencies]
arena = { workspace = true }
arena-container = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
log = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
env_logger = { workspace = true }