[package]
name = "arena-mssql"
version.workspace = true
edition = "2021"
authors = ["David Pope"]
description = "Arena Microsoft SQL Server implementation"
license = "todo"

[dependencies]
arena = { workspace = true }
arena-container = { workspace = true }
async-trait = { workspace = true }
testcontainers-modules = { workspace = true, features = ["mssql_server"] }
log = { workspace = true }
futures = { workspace = true }
tiberius = { workspace = true }
tokio = { workspace = true, features = ["rt", "net", "macros"] }
tokio-util = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
env_logger = { workspace = true }
