<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>ArenaDotnet.Xunit</RootNamespace>
    <AssemblyName>ArenaDotnet.Xunit</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PackageId>ArenaDotnet.Xunit</PackageId>
    <Authors>David Pope</Authors>
    <Description>xUnit integration for Arena</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/daveepope/arena.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/daveepope/arena</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.core" Version="2.9.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.2" />
  </ItemGroup>

</Project>
