[package]
name = "arena-examples"
version = "0.1.0"
edition = "2021"
authors = ["David Pope"]
description = "Examples using the arena framework. Intended as documentation and for testing."
license = "BSD 3-Claus"

[dependencies]
arena = { workspace = true }
arena-kafka = { workspace = true }
arena-postgres = { workspace = true }