[package]
name = "arena-examples"
version = "0.1.0"
edition = "2021"
authors = ["David Pope"]
description = "Examples using the arena framework. Intended as documentation and testing."
license = "BSD-3-Clause"

[dependencies]
arena = { workspace = true }
arena-kafka = { workspace = true }
arena-postgres = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
env_logger = { workspace = true }
log = { workspace = true }
