[package]
name = "arena-examples"
version.workspace = true
edition = "2021"
authors = ["David Pope"]
description = "Examples using the arena framework. Intended as documentation and testing."
license = "todo"

[lib]
name = "arena_examples"
path = "src/lib.rs"

[[bin]]
name = "arena-examples"
path = "src/example-arena-console/main.rs"

[[bin]]
name = "web-app"
path = "src/example-web-app/main.rs"

[dependencies]
arena = { workspace = true }
arena-kafka = { workspace = true }
arena-postgres = { workspace = true }
arena-executable-component = { workspace = true }
arena-container-component = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "net", "sync"] }
env_logger = { workspace = true }
log = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio-postgres = { workspace = true }
rdkafka = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
async-trait = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }

[[test]]
name = "component_test"
path = "tests/example-arena-component-test/component_test.rs"

[dev-dependencies]
rstest = { workspace = true }
ctor = "0.4"