[package]
name = "arena-oracledb"
version.workspace = true
edition = "2021"
authors = ["David Pope"]
description = "Arena Oracle DB implementation"
license = "todo"

[dependencies]
arena = { workspace = true }
arena-container = { workspace = true }
async-trait = { workspace = true }
testcontainers-modules = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
futures-timer = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "io-util", "time", "sync", "rt"] }

[dev-dependencies]
arena-host = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time", "net", "io-util", "sync"] }
tracing-subscriber = { workspace = true }
