#!/usr/bin/env python3

from __future__ import annotations

import os
import sys
from pathlib import Path

MARKER = "# generated by scripts/setup_local_bazelrc.py"


def _repo_root() -> Path:
    ws = os.environ.get("BUILD_WORKSPACE_DIRECTORY")
    if ws:
        return Path(ws)
    return Path(__file__).resolve().parent.parent


def main() -> int:
    api_key = os.environ.get("BUILDBUDDY_API_KEY", "").strip()
    if not api_key:
        print("BUILDBUDDY_API_KEY is not set in the environment; nothing to write", file=sys.stderr)
        return 1

    bazelrc_user = _repo_root() / ".bazelrc.user"
    lines = [
        MARKER,
        f"common --remote_header=x-buildbuddy-api-key={api_key}",
        "common --remote_cache=grpcs://arena.buildbuddy.io",
        "common --remote_timeout=10m",
        "build --bes_backend=grpcs://arena.buildbuddy.io",
        "build --bes_results_url=https://arena.buildbuddy.io/invocation/",
    ]

    existing = bazelrc_user.read_text() if bazelrc_user.exists() else ""
    kept = [
        line
        for line in existing.splitlines()
        if MARKER not in line
        and "x-buildbuddy-api-key" not in line
        and "remote_cache=grpcs://arena.buildbuddy.io" not in line
        and "remote_timeout=10m" not in line
        and "bes_backend=grpcs://arena.buildbuddy.io" not in line
        and "bes_results_url=https://arena.buildbuddy.io" not in line
    ]

    bazelrc_user.write_text("\n".join(kept + lines) + "\n")
    print(f"wrote BuildBuddy remote cache config to {bazelrc_user}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
