[package]
name = "arena-postgres"
version = "0.1.0"
edition = "2021"
authors = ["David Pope"]
description = "Arena Postgres implmentation"
license = "BSD-3-Clause"

[dependencies]
arena = { workspace = true }
async-trait = "0.1"
testcontainers-modules = { version = "0.14.0", features = ["postgres"] }
log = "0.4"
tokio = { version = "1", features = ["time"] }
tokio-postgres = "0.7"