[package]
name = "arena-postgres"
version.workspace = true
edition = "2021"
authors = ["David Pope"]
description = "Arena Postgres implementation"
license = "todo"

[dependencies]
arena = { workspace = true }
arena-container = { workspace = true }
async-trait = { workspace = true }
testcontainers-modules = { workspace = true, features = ["postgres"] }
tracing = { workspace = true }
futures = { workspace = true }
postgres = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { workspace = true }