[package]
name = "arena-postgres"
version = "0.1.0-alpha.1"
edition = "2021"
authors = ["David Pope"]
description = "Arena Postgres implementation"
license = "BSD-3-Clause"

[dependencies]
arena = { workspace = true }
async-trait = { workspace = true }
testcontainers-modules = { workspace = true, features = ["postgres"] }
log = { workspace = true }
futures = { workspace = true }
postgres = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
env_logger = { workspace = true }