name: DCO Check

on:
  pull_request:

jobs:
  dco-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: DCO Check
        uses: christophebedard/dco-check@v3
        with:
          exclude-emails: "dependabot[bot]@users.noreply.github.com"
