name: Dependency Review

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read
  pull-requests: read

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 2

      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294
        with:
          fail-on-severity: moderate
          base-ref: ${{ github.event_name == 'push' && 'HEAD~1' || '' }}
          head-ref: ${{ github.event_name == 'push' && 'HEAD' || '' }}
          allow-ghsas: GHSA-82j2-j2ch-gfr8
