name: OSV-Scanner

on:
  pull_request:
    branches: [ "master" ]
  merge_group:
    branches: [ "master" ]
  schedule:
    - cron: '17 6 * * 3'
  push:
    branches: [ "master" ]

permissions: read-all

jobs:
  scan-scheduled:
    if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
    permissions:
      security-events: write
      contents: read
      actions: read
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@8deb546fdb875b9996d27d4950be7312dac076a1
    with:
      fail-on-vuln: true
      scan-args: |-
        -r
        --skip-git
        ./
  scan-pr:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
    permissions:
      security-events: write
      contents: read
      actions: read
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@8deb546fdb875b9996d27d4950be7312dac076a1
    with:
      fail-on-vuln: true
      scan-args: |-
        -r
        --skip-git
        ./
